version: "3.9"
services:
  app:
    command: npm run dev
    build:
      context: ./web
      dockerfile: ../web.Dockerfile
    networks:
      - webnet
    develop:
      watch:
        - path: ./web
          target: /var/web # WORKDIR in Dockerfile
          action: sync
          ignore:
            - node_modules/
        - path: ./web/package.json
          target: /var/web/package.json
          action: rebuild
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  postgres:
    image: postgres:16.2
    networks:
      - webnet
    environment:
      POSTGRES_DB: error418_DB
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d error418_DB -U db_user"]
        interval: 10s
        timeout: 5s
        retries: 5

networks:
  webnet:
    driver: bridge