name: Deploy to Azure

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove watch rules
        run: |
          sed -i '/develop:/,/action: rebuild/d' compose.yml

      - name: Insert SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_RSA_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy repo contents to VM
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          remote_path: /home/${{ secrets.VM_USERNAME }}/${{ github.event.repository.name }}
          remote_host: ${{ secrets.VM_HOST }}
          remote_port: ${{ secrets.VM_PORT }}
          remote_user: ${{ secrets.VM_USERNAME }}
          remote_key: ${{ secrets.VM_RSA_PRIVATE_KEY }}

      - name: Connect and compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_RSA_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd /home/${{ secrets.VM_USERNAME }}/${{ github.event.repository.name }}
            ls -al
            docker-compose up --build -d
            exit