name: Tag and release
on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  tag_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        DEFAULT_BUMP: patch
        WITH_V: true
        RELEASE_BRANCHES:
        DRY_RUN: false
        INITIAL_VERSION: 0.0.0
        TAG_CONTEXT: repo
        VERBOSE: true
        MAJOR_STRING_TOKEN: major
        MINOR_STRING_TOKEN: minor
        PATCH_STRING_TOKEN: patch
        NONE_STRING_TOKEN: nobump
    - name: Create GitHub release
      uses: Roang-zero1/github-create-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        created_tag: ${{ steps.tag.outputs.new_tag }}
        create_draft: false