name: Node.js CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

defaults:
  run:
    working-directory: web

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install NPM dependencies
      run: npm ci
    - name: Build app
      run: npm run build --if-present
    - name: Run test suite
      run: npm test
    - name: Install Coveralls
      run: |
        curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin
        chmod +x /usr/local/bin/coveralls
        coveralls --version
    - name: Report coverage to Coveralls
      run: coveralls report ./coverage/lcov.info -r ${{ secrets.COVERALLS_REPO_TOKEN}}
    - name: Convert coverage report to markdown
      uses: fingerprintjs/action-coverage-report-md@v2
      id: coverage
      with:
        srcBasePath: './'
        textReportPath: './coverage/coverage.txt'
    - name: Add coverage report to the PR
      uses: mshick/add-pr-comment@v2
      with:
        message: ${{ steps.coverage.outputs.markdownReport }}
    - name: Add coverage report to the job summary
      run: |
        echo "### Code Coverage" >> $GITHUB_STEP_SUMMARY
        echo "${{ steps.coverage.outputs.markdownReport }}" >> $GITHUB_STEP_SUMMARY